# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.setWindowModality(QtCore.Qt.ApplicationModal)
        Window.resize(1034, 579)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(9)
        Window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-scatter-plot-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window.setWindowIcon(icon)
        Window.setAutoFillBackground(False)
        Window.setStyleSheet("border : none;\n"
"background-color : rgb(53,53,53);\n"
"\n"
"\n"
"")
        Window.setDockNestingEnabled(False)
        Window.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopFrame = QtWidgets.QFrame(self.centralwidget)
        self.TopFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame.setObjectName("TopFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TopFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TopMenu = QtWidgets.QFrame(self.TopFrame)
        self.TopMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TopMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopMenu.setObjectName("TopMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.TopMenu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FrameMenu = QtWidgets.QFrame(self.TopMenu)
        self.FrameMenu.setStyleSheet("QPushButton:hover{\n"
"    border-bottom : 0.5px solid rgba(165, 254, 255, 150);\n"
"     border-right : 0.5px solid rgba(185, 254, 255, 150);\n"
"     border-bottom-right-radius : 5px;\n"
"}")
        self.FrameMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameMenu.setObjectName("FrameMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.FrameMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MenuBtn = QtWidgets.QPushButton(self.FrameMenu)
        self.MenuBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-menu-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuBtn.setIcon(icon1)
        self.MenuBtn.setIconSize(QtCore.QSize(45, 45))
        self.MenuBtn.setCheckable(False)
        self.MenuBtn.setAutoRepeat(False)
        self.MenuBtn.setAutoExclusive(False)
        self.MenuBtn.setAutoDefault(False)
        self.MenuBtn.setDefault(False)
        self.MenuBtn.setFlat(False)
        self.MenuBtn.setObjectName("MenuBtn")
        self.verticalLayout_9.addWidget(self.MenuBtn)
        self.horizontalLayout.addWidget(self.FrameMenu)
        self.Label_Home_2 = QtWidgets.QLabel(self.TopMenu)
        self.Label_Home_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.Label_Home_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Label_Home_2.setFont(font)
        self.Label_Home_2.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Label_Home_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_Home_2.setLineWidth(0)
        self.Label_Home_2.setObjectName("Label_Home_2")
        self.horizontalLayout.addWidget(self.Label_Home_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.TopMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ConnectionBtn = QtWidgets.QPushButton(self.frame)
        self.ConnectionBtn.setStyleSheet("color : green;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-internet-antenna-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ConnectionBtn.setIcon(icon2)
        self.ConnectionBtn.setIconSize(QtCore.QSize(40, 24))
        self.ConnectionBtn.setObjectName("ConnectionBtn")
        self.verticalLayout_4.addWidget(self.ConnectionBtn)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.windows_Buttons = QtWidgets.QFrame(self.TopMenu)
        self.windows_Buttons.setStyleSheet("QPushButton{margin:2px;}\n"
"\n"
"#Close_btn{\n"
"    border-left : 0.5px solid black;\n"
"    border-bottom-left-radius : 3;\n"
"    \n"
"}\n"
"#Minimize_btn{\n"
"    border-right : 0.5px solid black;\n"
"    border-bottom-right-radius : 3;\n"
"    \n"
"}\n"
"/* Hover */\n"
"#Close_btn:hover{\n"
"    border-left : 0.7px solid black;\n"
"    border-top-left-radius : 3;\n"
"    border-bottom-left-radius : 0;\n"
"    background-color : rgba(230, 0, 0, 55);\n"
"    \n"
"    \n"
"}\n"
"\n"
"#Maximize_btn:hover{\n"
"    background-color : rgba(0, 0, 235, 55);\n"
"    \n"
"}\n"
"\n"
"#Minimize_btn:hover{\n"
"    border-right : 0.7px solid black;\n"
"    border-top-right-radius : 3;\n"
"    border-bottom-left-radius : 0;\n"
"    background-color : rgba(250, 250, 250, 55);\n"
"    \n"
"}\n"
"")
        self.windows_Buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.windows_Buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.windows_Buttons.setObjectName("windows_Buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.windows_Buttons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Minimize_btn = QtWidgets.QPushButton(self.windows_Buttons)
        self.Minimize_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-advertisement-page-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize_btn.setIcon(icon3)
        self.Minimize_btn.setIconSize(QtCore.QSize(32, 32))
        self.Minimize_btn.setObjectName("Minimize_btn")
        self.horizontalLayout_2.addWidget(self.Minimize_btn)
        self.Maximize_btn = QtWidgets.QPushButton(self.windows_Buttons)
        self.Maximize_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-maximize-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Maximize_btn.setIcon(icon4)
        self.Maximize_btn.setIconSize(QtCore.QSize(32, 32))
        self.Maximize_btn.setObjectName("Maximize_btn")
        self.horizontalLayout_2.addWidget(self.Maximize_btn)
        self.Close_btn = QtWidgets.QPushButton(self.windows_Buttons)
        self.Close_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-close-window-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close_btn.setIcon(icon5)
        self.Close_btn.setIconSize(QtCore.QSize(32, 32))
        self.Close_btn.setObjectName("Close_btn")
        self.horizontalLayout_2.addWidget(self.Close_btn)
        self.horizontalLayout.addWidget(self.windows_Buttons, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.TopMenu)
        self.verticalLayout.addWidget(self.TopFrame)
        self.BottomFrame = QtWidgets.QFrame(self.centralwidget)
        self.BottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomFrame.setObjectName("BottomFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.BottomFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LeftMenuFrame = QtWidgets.QFrame(self.BottomFrame)
        self.LeftMenuFrame.setStyleSheet("QFrame {\n"
"    border-right : 0.5px solid rgba(29, 29, 29, 100);\n"
"    border-bottom:0.5px solid rgba(4, 4, 4, 50);\n"
"    border-bottom-right-radius : 12px;\n"
"}\n"
"\n"
"QFrame:hover{\n"
"    border-right : 0.5px solid rgba(75, 255, 243, 150);\n"
"    border-bottom:0.5px solid rgba(4, 4, 4, 150);\n"
"}\n"
"")
        self.LeftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LeftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LeftMenuFrame.setObjectName("LeftMenuFrame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.LeftMenuFrame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.FrameHome = QtWidgets.QFrame(self.LeftMenuFrame)
        self.FrameHome.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameHome.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameHome.setObjectName("FrameHome")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.FrameHome)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.HomeBtn = QtWidgets.QPushButton(self.FrameHome)
        self.HomeBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-home-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeBtn.setIcon(icon6)
        self.HomeBtn.setIconSize(QtCore.QSize(45, 45))
        self.HomeBtn.setObjectName("HomeBtn")
        self.verticalLayout_10.addWidget(self.HomeBtn)
        self.verticalLayout_8.addWidget(self.FrameHome)
        self.FrameAccount = QtWidgets.QFrame(self.LeftMenuFrame)
        self.FrameAccount.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameAccount.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameAccount.setObjectName("FrameAccount")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.FrameAccount)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.AccountBtn = QtWidgets.QPushButton(self.FrameAccount)
        self.AccountBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-male-user-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AccountBtn.setIcon(icon7)
        self.AccountBtn.setIconSize(QtCore.QSize(45, 45))
        self.AccountBtn.setObjectName("AccountBtn")
        self.verticalLayout_11.addWidget(self.AccountBtn)
        self.verticalLayout_8.addWidget(self.FrameAccount)
        self.FrameTrading = QtWidgets.QFrame(self.LeftMenuFrame)
        self.FrameTrading.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameTrading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameTrading.setObjectName("FrameTrading")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.FrameTrading)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TradingBtn = QtWidgets.QPushButton(self.FrameTrading)
        self.TradingBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-trading-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TradingBtn.setIcon(icon8)
        self.TradingBtn.setIconSize(QtCore.QSize(45, 45))
        self.TradingBtn.setObjectName("TradingBtn")
        self.verticalLayout_12.addWidget(self.TradingBtn)
        self.verticalLayout_8.addWidget(self.FrameTrading)
        self.FrameSetting = QtWidgets.QFrame(self.LeftMenuFrame)
        self.FrameSetting.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameSetting.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameSetting.setObjectName("FrameSetting")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.FrameSetting)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.SettingBtn = QtWidgets.QPushButton(self.FrameSetting)
        self.SettingBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-settings-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingBtn.setIcon(icon9)
        self.SettingBtn.setIconSize(QtCore.QSize(45, 45))
        self.SettingBtn.setObjectName("SettingBtn")
        self.verticalLayout_13.addWidget(self.SettingBtn)
        self.verticalLayout_8.addWidget(self.FrameSetting)
        self.FrameAbout = QtWidgets.QFrame(self.LeftMenuFrame)
        self.FrameAbout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FrameAbout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FrameAbout.setObjectName("FrameAbout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.FrameAbout)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.AboutBtn = QtWidgets.QPushButton(self.FrameAbout)
        self.AboutBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/icons/icons8-about-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AboutBtn.setIcon(icon10)
        self.AboutBtn.setIconSize(QtCore.QSize(45, 45))
        self.AboutBtn.setObjectName("AboutBtn")
        self.verticalLayout_14.addWidget(self.AboutBtn)
        self.verticalLayout_8.addWidget(self.FrameAbout)
        self.horizontalLayout_3.addWidget(self.LeftMenuFrame)
        self.LabelFrame = QtWidgets.QFrame(self.BottomFrame)
        self.LabelFrame.setStyleSheet("QFrame:hover{\n"
"    border-right : 0.5px solid rgba(27, 176, 176, 150);\n"
"    border-bottom : 0.5px solid rgba(27, 176, 176, 220);\n"
"    border-left : 0.5px solid rgba(102, 234, 175, 150);\n"
"    border-top : 0.5px solid rgba(162, 229, 201, 200);\n"
"    border-top-left-radius:0;\n"
"    border-bottom-right-radius:10px;    \n"
"}\n"
"")
        self.LabelFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.LabelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LabelFrame.setObjectName("LabelFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.LabelFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.HomeFrameLabel = QtWidgets.QFrame(self.LabelFrame)
        self.HomeFrameLabel.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.HomeFrameLabel.setAcceptDrops(False)
        self.HomeFrameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HomeFrameLabel.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.HomeFrameLabel.setObjectName("HomeFrameLabel")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.HomeFrameLabel)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Label_Home = QtWidgets.QLabel(self.HomeFrameLabel)
        self.Label_Home.setSizeIncrement(QtCore.QSize(0, 0))
        self.Label_Home.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Label_Home.setFont(font)
        self.Label_Home.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Label_Home.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_Home.setLineWidth(0)
        self.Label_Home.setObjectName("Label_Home")
        self.horizontalLayout_5.addWidget(self.Label_Home)
        self.verticalLayout_3.addWidget(self.HomeFrameLabel)
        self.Label_Account = QtWidgets.QLabel(self.LabelFrame)
        self.Label_Account.setSizeIncrement(QtCore.QSize(0, 0))
        self.Label_Account.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Label_Account.setFont(font)
        self.Label_Account.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Label_Account.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_Account.setLineWidth(0)
        self.Label_Account.setIndent(0)
        self.Label_Account.setObjectName("Label_Account")
        self.verticalLayout_3.addWidget(self.Label_Account)
        self.HomeFrameLabel_2 = QtWidgets.QFrame(self.LabelFrame)
        self.HomeFrameLabel_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.HomeFrameLabel_2.setAcceptDrops(False)
        self.HomeFrameLabel_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HomeFrameLabel_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.HomeFrameLabel_2.setObjectName("HomeFrameLabel_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.HomeFrameLabel_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Label_Home_3 = QtWidgets.QLabel(self.HomeFrameLabel_2)
        self.Label_Home_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.Label_Home_3.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Label_Home_3.setFont(font)
        self.Label_Home_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Label_Home_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_Home_3.setLineWidth(0)
        self.Label_Home_3.setObjectName("Label_Home_3")
        self.horizontalLayout_6.addWidget(self.Label_Home_3)
        self.verticalLayout_3.addWidget(self.HomeFrameLabel_2)
        self.HomeFrameLabel_3 = QtWidgets.QFrame(self.LabelFrame)
        self.HomeFrameLabel_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.HomeFrameLabel_3.setAcceptDrops(False)
        self.HomeFrameLabel_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HomeFrameLabel_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.HomeFrameLabel_3.setObjectName("HomeFrameLabel_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.HomeFrameLabel_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Label_Home_4 = QtWidgets.QLabel(self.HomeFrameLabel_3)
        self.Label_Home_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.Label_Home_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Label_Home_4.setFont(font)
        self.Label_Home_4.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Label_Home_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_Home_4.setLineWidth(0)
        self.Label_Home_4.setObjectName("Label_Home_4")
        self.horizontalLayout_7.addWidget(self.Label_Home_4)
        self.verticalLayout_3.addWidget(self.HomeFrameLabel_3)
        self.HomeFrameLabel_4 = QtWidgets.QFrame(self.LabelFrame)
        self.HomeFrameLabel_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.HomeFrameLabel_4.setAcceptDrops(False)
        self.HomeFrameLabel_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HomeFrameLabel_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.HomeFrameLabel_4.setObjectName("HomeFrameLabel_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.HomeFrameLabel_4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Label_Home_5 = QtWidgets.QLabel(self.HomeFrameLabel_4)
        self.Label_Home_5.setSizeIncrement(QtCore.QSize(0, 0))
        self.Label_Home_5.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.Label_Home_5.setFont(font)
        self.Label_Home_5.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.Label_Home_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Label_Home_5.setLineWidth(0)
        self.Label_Home_5.setObjectName("Label_Home_5")
        self.horizontalLayout_8.addWidget(self.Label_Home_5)
        self.verticalLayout_3.addWidget(self.HomeFrameLabel_4)
        self.horizontalLayout_3.addWidget(self.LabelFrame)
        self.Views = QtWidgets.QStackedWidget(self.BottomFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Views.sizePolicy().hasHeightForWidth())
        self.Views.setSizePolicy(sizePolicy)
        self.Views.setStyleSheet("")
        self.Views.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Views.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Views.setObjectName("Views")
        self.PageHome = QtWidgets.QWidget()
        self.PageHome.setObjectName("PageHome")
        self.Views.addWidget(self.PageHome)
        self.horizontalLayout_3.addWidget(self.Views)
        self.verticalLayout.addWidget(self.BottomFrame)
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        self.Views.setCurrentIndex(0)
        self.Close_btn.clicked.connect(Window.close)
        self.Maximize_btn.clicked.connect(Window.showMaximized)
        self.Minimize_btn.clicked.connect(Window.showMinimized)
        self.MenuBtn.clicked['bool'].connect(self.LabelFrame.update)
        self.ConnectionBtn.clicked.connect(self.ConnectionBtn.update)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "MainWindow"))
        self.Label_Home_2.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#6286b5;\">Menu</span></p></body></html>"))
        self.ConnectionBtn.setText(_translate("Window", "Connected"))
        self.Label_Home.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#6286b5;\">Home</span></p></body></html>"))
        self.Label_Account.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#6286b5;\">Account</span></p></body></html>"))
        self.Label_Home_3.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#6286b5;\">Trading</span></p></body></html>"))
        self.Label_Home_4.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#6286b5;\">Setting</span></p></body></html>"))
        self.Label_Home_5.setText(_translate("Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#6286b5;\">About Us</span></p></body></html>"))

import resourse_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())

